<?php

// Generated by Haxe 3.4.2
class runtime_proxies_QkObject {
	public function __construct($name) {
		if(!php_Boot::$skip_constructor) {
		$this->name = $name;
	}}
	public $name;
	public function callFn($functionName, $args, $map) {
	}
	public function creationService() {
		return _hx_anonymous(array());
	}
	public function getId() {
		return -1;
	}
	public function getProperty($propertyName) {
		return null;
	}
	public function setProperty($propertyName, $val, $map) {
	}
	public function toString() {
		return "QkObject(" . _hx_string_or_null($this->name) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
