<?php

// Generated by Haxe 3.4.2
class runtime_proxies_QkProxyObject extends runtime_proxies_QkObject {
	public function __construct($name) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct($name);
		$this->proxyId = ++runtime_proxies_QkProxyObject::$idCounter;
	}}
	public $proxyId;
	public function addModuleHandler($moduleName, $subName, $eventName, $map) {
		$map->set("id", $this->proxyId);
		$map->set("type", "module");
		$map->set("module", $moduleName);
		$map->set("subroutine", $subName);
		$map->set("event", $eventName);
	}
	public function callFn($functionName, $args, $map) {
		$map->set("action", $functionName);
		$map->set("args", $args);
	}
	public function getId() {
		return $this->proxyId;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $idCounter = 0;
	function __toString() { return 'runtime.proxies.QkProxyObject'; }
}
