<?php

// Generated by Haxe 3.4.2
class runtime_Vm {
	public function __construct(){}
	static function evalScript($script, $sessionStr) {
		runtime_Vm::restoreFromSession($sessionStr);
		return runtime_Vm::runScript(runtime_Vm::addLibs($script));
	}
	static function addLibs($script) {
		$lib1 = sys_io_File::getContent("./vb/lib1.vb");
		return "" . _hx_string_or_null($lib1) . "\x0A\x0A" . _hx_string_or_null($script) . "\x0A\x0A";
	}
	static function runScript($script) {
		$src = "" . _hx_string_or_null($script) . "\x0A\x0A";
		$method = compiler_Compiler::compileScript($src);
		$returnValues = (new _hx_array(array()));
		$returnValues->push(runtime_Vm::runMethod($method));
		$returnValues->push(runtime_Vm::storeToSession());
		return $returnValues;
	}
	static function runMethod($method) {
		$bytecodes = $method->bytecodes;
		$literals = $method->literals;
		$process = new runtime_Process($bytecodes, $literals);
		return $process->run();
	}
	static function restoreFromSession($sessionStr) {
		if($sessionStr !== null) {
			runtime_SystemDictionary::$instance->fromSession($sessionStr);
		}
	}
	static function storeToSession() {
		return runtime_SystemDictionary::$instance->toSession();
	}
	function __toString() { return 'runtime.Vm'; }
}
