<?php

// Generated by Haxe 3.4.2
class runtime_Vm {
	public function __construct(){}
	static function callSubroutine($sessionStr, $id, $type, $moduleName, $subroutineName) {
		runtime_Vm::restoreFromSession($sessionStr);
		return runtime_Vm::wrapReply(runtime_Vm::runFromSubroutine($id, $type, $moduleName, $subroutineName));
	}
	static function classNames($sessionStr) {
		runtime_Vm::restoreFromSession($sessionStr);
		return runtime_Vm::wrapReply(runtime_globals_GlobalObjects::$objectClass->withAllSubClassNames());
	}
	static function evalScript($script, $sessionStr) {
		runtime_Vm::restoreFromSession($sessionStr);
		$reply = runtime_Vm::runFromScript($script);
		return runtime_Vm::wrapReply($reply);
	}
	static function runFromScript($script) {
		$src = "" . _hx_string_or_null($script) . "\x0A\x0A";
		$method = compiler_Compiler::compileScript($src);
		return runtime_process_ProcessManager::runMethod($method);
	}
	static function runFromSubroutine($id, $type, $moduleName, $subroutineName) {
		$module = runtime_globals_GlobalModules::getModule($moduleName);
		if($module === null) {
			return "module [" . _hx_string_or_null($moduleName) . "] not found";
		}
		$method = $module->getMethod($subroutineName);
		if($method === null) {
			return "module [" . _hx_string_or_null($moduleName) . "] method [" . _hx_string_or_null($subroutineName) . "] not found";
		}
		return runtime_process_ProcessManager::runMethod($method);
	}
	static function wrapReply($reply) {
		$values = (new _hx_array(array()));
		$values->push($reply);
		$values->push(runtime_Vm::storeToSession());
		return $values;
	}
	static function restoreFromSession($sessionStr) {
		runtime_loader_SessionManager::restoreFromSession($sessionStr);
	}
	static function storeToSession() {
		return runtime_loader_SessionManager::storeToSession();
	}
	function __toString() { return 'runtime.Vm'; }
}
