<?php

// Generated by Haxe 3.4.2
class runtime_modules_ClassModule extends runtime_modules_AbstractModule {
	public function __construct($name, $propertyNames = null) { if(!php_Boot::$skip_constructor) {
		parent::__construct($name,$propertyNames);
	}}
	function __toString() { return 'runtime.modules.ClassModule'; }
}
