<?php

// Generated by Haxe 3.4.2
class runtime_modules_StdModule extends runtime_modules_AbstractModule {
	public function __construct($name, $propertyNames = null) { if(!php_Boot::$skip_constructor) {
		parent::__construct($name,$propertyNames);
	}}
	public function toString() {
		return "StdModule(" . _hx_string_or_null($this->name) . ")";
	}
	static function findOrCreate($name) {
		$module = runtime_globals_GlobalModules::getStdModule($name);
		if($module !== null) {
			return $module;
		}
		$module = new runtime_modules_StdModule($name, null);
		return runtime_globals_GlobalModules::setStdModule($name, $module);
	}
	function __toString() { return $this->toString(); }
}
