<?php

// Generated by Haxe 3.4.2
class runtime_globals_GlobalModules {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$this->modules = new haxe_ds_StringMap();
	}}
	public $modules;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $instance;
	static $messages;
	static function clearMessages() {
		runtime_globals_GlobalModules::$messages = (new _hx_array(array()));
	}
	static function getModule($name) {
		return runtime_globals_GlobalModules::$instance->modules->get($name);
	}
	static function getModules() {
		return runtime_globals_GlobalModules::$instance->modules;
	}
	static function printMessage($msg) {
		runtime_globals_GlobalModules::$messages->push($msg);
	}
	static function setModule($name, $module) {
		runtime_globals_GlobalModules::$instance->modules->set($name, $module);
		return $module;
	}
	static function setModules($modules) {
		runtime_globals_GlobalModules::$instance->modules = $modules;
	}
	function __toString() { return 'runtime.globals.GlobalModules'; }
}
runtime_globals_GlobalModules::$instance = new runtime_globals_GlobalModules();
runtime_globals_GlobalModules::$messages = (new _hx_array(array()));
