<?php

// Generated by Haxe 3.4.2
class runtime_globals_GlobalObjects {
	public function __construct(){}
	static $metaClassClass = null;
	static $arrayClass = null;
	static $basicReaderClass = null;
	static $behaviorClass = null;
	static $blockContextClass = null;
	static $booleanClass = null;
	static $classClass = null;
	static $collectionClass = null;
	static $compiledMethodClass = null;
	static $compilerClass = null;
	static $contextClass = null;
	static $databaseClass = null;
	static $dictionaryClass = null;
	static $falseClass = null;
	static $floatClass = null;
	static $globalDictionaryClass = null;
	static $inputOutputClass = null;
	static $integerClass = null;
	static $kernelClass = null;
	static $listClass = null;
	static $magnitudeClass = null;
	static $messageClass = null;
	static $methodContextClass = null;
	static $numberClass = null;
	static $objectClass = null;
	static $orderedCollectionClass = null;
	static $processorClass = null;
	static $proxyClass = null;
	static $stringClass = null;
	static $systemClass = null;
	static $trueClass = null;
	static $undefinedObjectClass = null;
	static $vmClass = null;
	function __toString() { return 'runtime.globals.GlobalObjects'; }
}
