<?php

// Generated by Haxe 3.4.2
class compiler_Compiler {
	public function __construct() {}
	public function compileFromScript($script) {
		$procedure = parser_Parser::parse($script);
		return $this->generateCompiledMethod($procedure);
	}
	public function generateCompiledMethod($procedure) {
		$bytecodes = new _hx_array(array());
		$util = new compiler_CompilerUtil();
		$procedure->generate($bytecodes, $util);
		return new compiler_CompiledMethod($bytecodes, $util->literals);
	}
	static function compileScript($src) {
		$compilerMethod = _hx_deref(new compiler_Compiler())->compileFromScript($src);
		$compilerMethod->src = $src;
		return $compilerMethod;
	}
	function __toString() { return 'compiler.Compiler'; }
}
