<?php

// Generated by Haxe 3.4.2
class compiler_CompilerUtil {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$this->literals = new _hx_array(array());
	}}
	public $literals;
	public function encodeLiteral($literal) {
		if($this->literals->indexOf($literal, null) < 0) {
			$this->literals->push($literal);
		}
		return $this->literals->indexOf($literal, null);
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'compiler.CompilerUtil'; }
}
