<?php

// Generated by Haxe 3.4.2
class Vb {
	public function __construct(){}
	static function main() {
		runtime_loader_ObjectBuilder::init();
	}
	static function getScript($fname) {
		$path = "./vb/" . _hx_string_or_null($fname) . ".vb";
		return sys_io_File::getContent($path);
	}
	static function runScript($fname) {
		$script = Vb::getScript($fname);
		runtime_Vm::evalScript($script, null);
	}
	function __toString() { return 'Vb'; }
}
