<?php

// Generated by Haxe 3.4.2
class runtime_objects_VBehavior extends runtime_objects_VObject {
	public function __construct($vclass, $varNames) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct($vclass);
		$this->methodCache = new haxe_ds_StringMap();
		$this->methodDict = new haxe_ds_StringMap();
		$this->superClass = null;
		$tmp = null;
		if($varNames !== null) {
			$tmp = $varNames;
		} else {
			$tmp = (new _hx_array(array()));
		}
		$this->varNames = $tmp;
	}}
	public $methodCache;
	public $methodDict;
	public $superClass;
	public $varNames;
	public function addSubClass($subClass) {
	}
	public function getClass() {
		return null;
	}
	public function setSuperClass($superClass) {
		$this->superClass = $superClass;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'runtime.objects.VBehavior'; }
}
