<?php

// Generated by Haxe 3.4.2
class runtime_objects_VMetaClass extends runtime_objects_VBehavior {
	public function __construct($thisClass = null, $classVars = null) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct(runtime_globals_GlobalObjects::$metaClassClass,$classVars);
		$this->thisClass = $thisClass;
	}}
	public $thisClass;
	public function toString() {
		$name = $this->thisClass->name;
		return "" . _hx_string_or_null($name) . " class";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
