<?php

// Generated by Haxe 3.4.2
class parser_nodes_DimensionNode extends parser_nodes_ParseNode {
	public function __construct($name, $type = null) {
		if(!php_Boot::$skip_constructor) {
		if($type === null) {
			$type = 1;
		}
		parent::__construct();
		$this->name = $name->unsetGlobal();
		$this->type = $type;
	}}
	public $name;
	public $type;
	public function generate($bytecodes, $util) {
		$tmp = $this->name->getName();
		runtime_proxies_ProxyManager::ensureProxy($tmp, $this->type);
		$bytecodes->push(2);
		$this->name->generate($bytecodes, $util);
		$bytecodes->push($this->type);
	}
	public function toString() {
		$s = $this->name->getName();
		return "DimensionNode(" . _hx_string_or_null($s) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
