<?php

// Generated by Haxe 3.4.2
class parser_nodes_DimensionNode extends parser_nodes_ParseNode {
	public function __construct($module, $name, $type = null) {
		if(!php_Boot::$skip_constructor) {
		if($type === null) {
			$type = 1;
		}
		parent::__construct();
		$this->module = $module;
		$this->name = $name;
		$this->type = $type;
	}}
	public $module;
	public $name;
	public $type;
	public function generate($bytecodes, $util) {
		runtime_proxies_ProxyManager::ensureProxy($this->module, $this->name, $this->type);
		$bytecodes->push(2);
		$bytecodes->push($util->encodeLiteral($this->module));
		$bytecodes->push($util->encodeLiteral($this->name));
	}
	public function toString() {
		return "DimensionNode(" . _hx_string_or_null($this->module) . ", " . _hx_string_or_null($this->name) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
