<?php

// Generated by Haxe 3.4.2
class parser_nodes_ErrorNode extends parser_nodes_ParseNode {
	public function __construct($token) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->token = $token;
	}}
	public $token;
	public function generate($bytecodes, $util) {
	}
	public function toString() {
		$s = Std::string($this->token);
		return "ErrorNode(" . _hx_string_or_null($s) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
