<?php

// Generated by Haxe 3.4.2
class parser_nodes_MethodNode extends parser_nodes_ParseNode {
	public function __construct($statementBlock) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->statementBlock = $statementBlock;
	}}
	public $statementBlock;
	public function generate($bytecodes, $util) {
		if($this->statementBlock !== null) {
			$this->statementBlock->generate($bytecodes, $util);
		}
	}
	public function toString() {
		$sbstr = $this->statementBlock->toString();
		return "MethodNode(" . _hx_string_or_null($sbstr) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
