<?php

// Generated by Haxe 3.4.2
class parser_nodes_ParseNode {
	public function __construct() {}
	public function addArg($arg) {}
	public function addArgs($args) {
		$_g = 0;
		while($_g < $args->length) {
			$arg = $args[$_g];
			$_g = $_g + 1;
			$this->addArg($arg);
			unset($arg);
		}
	}
	public function addStmt($stmt) {}
	public function asBlockNode() {
		return null;
	}
	public function asSubroutineNode() {
		return null;
	}
	public function atEnd() {
		return false;
	}
	public function generate($bytecodes, $util) {}
	public function getName() {
		return "";
	}
	public function isClass() {
		return false;
	}
	public function isModule() {
		return false;
	}
	public function isSubroutine() {
		return false;
	}
	public function moduleName() {
		return "none";
	}
	public function toString() {
		return "a ParseNode";
	}
	public function unsetGlobal() {
		return $this;
	}
	function __toString() { return $this->toString(); }
}
