<?php

// Generated by Haxe 3.4.2
class parser_nodes_PropertyNode extends parser_nodes_ParseNode {
	public function __construct($objectName, $propertyName, $value = null) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->objectName = $objectName;
		$this->propertyName = $propertyName;
		$this->value = $value;
	}}
	public $objectName;
	public $propertyName;
	public $value;
	public function generate($bytecodes, $util) {
		if($this->value !== null) {
			$this->value->generate($bytecodes, $util);
			$bytecodes->push(16);
		} else {
			$bytecodes->push(19);
		}
		$bytecodes->push($util->encodeLiteral($this->objectName));
		$bytecodes->push($util->encodeLiteral($this->propertyName));
	}
	public function toString() {
		return "Property(" . _hx_string_or_null($this->objectName) . "." . _hx_string_or_null($this->propertyName) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
