<?php

// Generated by Haxe 3.4.2
class parser_nodes_StatementBlock extends parser_nodes_ParseNode {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->blockStmts = new _hx_array(array());
	}}
	public $blockStmts;
	public function addStmt($stmt) {
		$this->blockStmts->push($stmt);
	}
	public function generate($bytecodes, $util) {
		$_g1 = 0;
		$_g = $this->blockStmts->length;
		while($_g1 < $_g) {
			$_g1 = $_g1 + 1;
			$i = $_g1 - 1;
			$stmt = $this->blockStmts[$i];
			$stmt->generate($bytecodes, $util);
			if($i < $this->blockStmts->length - 1) {
				$bytecodes->push(14);
			}
			unset($stmt,$i);
		}
	}
	public function toString() {
		$len = $this->blockStmts->length;
		return "BlockNode(" . _hx_string_rec($len, "") . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
