<?php

// Generated by Haxe 3.4.2
class parser_nodes_SubroutineNode extends parser_nodes_BlockNode {
	public function __construct($name) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->name = $name->getName();
	}}
	public $name;
	public function asSubroutineNode() {
		return $this;
	}
	public function compile() {
		return compiler_Compiler::compileMethod(new parser_nodes_MethodNode($this));
	}
	public function isSubroutine() {
		return true;
	}
	public function toString() {
		return "SubroutineNode(" . _hx_string_or_null($this->name) . ")";
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
