<?php

// Generated by Haxe 3.4.2
class parser_nodes_VariableNode extends parser_nodes_ParseNode {
	public function __construct($varName) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->emitValue = true;
		$this->{"global"} = util_StringUtil::isGlobal($varName);
		$this->varName = $varName;
	}}
	public $emitValue;
	public $global;
	public $varName;
	public function generate($bytecodes, $util) {
		if($this->emitValue) {
			if($this->{"global"}) {
				$bytecodes->push(22);
			} else {
				$bytecodes->push(21);
			}
		}
		$bytecodes->push($util->encodeLiteral($this->varName));
	}
	public function getName() {
		return $this->varName;
	}
	public function isGlobal() {
		return $this->{"global"};
	}
	public function toString() {
		return "Variable(" . _hx_string_or_null($this->varName) . ")";
	}
	public function unsetEmitValue() {
		$this->emitValue = false;
		return $this;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
