<?php

// Generated by Haxe 3.4.2
class php_Lib {
	public function __construct(){}
	static function toPhpArray($a) {
		return $a->a;
	}
	static function associativeArrayOfHash($hash) {
		return $hash->h;
	}
	function __toString() { return 'php.Lib'; }
}
