<?php

// Generated by Haxe 3.4.2
class constants_Builtins {
	public function __construct(){}
	static $MsgBox = "msgbox";
	static $hPrint = "print";
	static $BuiltinNames;
	function __toString() { return 'constants.Builtins'; }
}
constants_Builtins::$BuiltinNames = (new _hx_array(array("msgbox", "print")));
