<?php

// Generated by Haxe 3.4.2
class constants_DimensionType {
	public function __construct(){}
	static $Any = 1;
	static $BasicEditor = 2;
	static $Button = 3;
	static $Canvas = 4;
	static $Database = 5;
	static $FormPanel = 6;
	static $HSplitPanel = 7;
	static $ListPanel = 8;
	static $RichEditor = 9;
	static $TabPage = 10;
	static $TabPanel = 11;
	static $TextArea = 12;
	static $TextField = 13;
	static $Window = 14;
	static $Viewport = 15;
	static $VSplitPanel = 16;
	function __toString() { return 'constants.DimensionType'; }
}
