<?php

// Generated by Haxe 3.4.2
class constants_DimensionType {
	public function __construct(){}
	static $Any = 1;
	static $BasicEditor = 2;
	static $Button = 3;
	static $Database = 4;
	static $FormPanel = 5;
	static $HSplitPanel = 6;
	static $ListPanel = 7;
	static $RichEditor = 8;
	static $TabPanel = 9;
	static $TextArea = 10;
	static $TextField = 11;
	static $Window = 12;
	static $Viewport = 13;
	static $VSplitPanel = 14;
	function __toString() { return 'constants.DimensionType'; }
}
