<?php

// Generated by Haxe 3.4.2
class constants_DimensionType {
	public function __construct(){}
	static $Any = 1;
	static $BasicEditor = 2;
	static $Button = 3;
	static $ButtonBar = 4;
	static $Canvas = 5;
	static $Database = 6;
	static $FormPanel = 7;
	static $HSplitPanel = 8;
	static $ListPanel = 9;
	static $MenuBarButton = 10;
	static $RichEditor = 11;
	static $TabPage = 12;
	static $TabPanel = 13;
	static $TextArea = 14;
	static $TextField = 15;
	static $Window = 16;
	static $Viewport = 17;
	static $VSplitPanel = 18;
	function __toString() { return 'constants.DimensionType'; }
}
