<?php

// Generated by Haxe 3.4.2
class constants_DimensionType extends Enum {
	public static $Any;
	public static $BasicEditor;
	public static $Button;
	public static $Database;
	public static $FormPanel;
	public static $ListPanel;
	public static $RichEditor;
	public static $TabPanel;
	public static $TextArea;
	public static $TextField;
	public static $Viewport;
	public static $Window;
	public static $__constructors = array(0 => 'Any', 1 => 'BasicEditor', 2 => 'Button', 3 => 'Database', 4 => 'FormPanel', 5 => 'ListPanel', 6 => 'RichEditor', 7 => 'TabPanel', 9 => 'TextArea', 8 => 'TextField', 11 => 'Viewport', 10 => 'Window');
	}
constants_DimensionType::$Any = new constants_DimensionType("Any", 0);
constants_DimensionType::$BasicEditor = new constants_DimensionType("BasicEditor", 1);
constants_DimensionType::$Button = new constants_DimensionType("Button", 2);
constants_DimensionType::$Database = new constants_DimensionType("Database", 3);
constants_DimensionType::$FormPanel = new constants_DimensionType("FormPanel", 4);
constants_DimensionType::$ListPanel = new constants_DimensionType("ListPanel", 5);
constants_DimensionType::$RichEditor = new constants_DimensionType("RichEditor", 6);
constants_DimensionType::$TabPanel = new constants_DimensionType("TabPanel", 7);
constants_DimensionType::$TextArea = new constants_DimensionType("TextArea", 9);
constants_DimensionType::$TextField = new constants_DimensionType("TextField", 8);
constants_DimensionType::$Viewport = new constants_DimensionType("Viewport", 11);
constants_DimensionType::$Window = new constants_DimensionType("Window", 10);
