<?php

// Generated by Haxe 3.4.2
class constants_Events {
	public function __construct(){}
	static $Click = "click";
	static $EventNames;
	function __toString() { return 'constants.Events'; }
}
constants_Events::$EventNames = (new _hx_array(array(constants_Events::$Click)));
