<?php

// Generated by Haxe 3.4.2
class constants_Opcode {
	public function __construct(){}
	static $CallMemberFn = 1;
	static $Dimension = 2;
	static $Divide = 3;
	static $Eq = 4;
	static $FnCall = 5;
	static $Gt = 6;
	static $Gte = 7;
	static $Jmp = 8;
	static $JmpIfFalse = 9;
	static $Lt = 10;
	static $Lte = 11;
	static $Minus = 12;
	static $Neq = 13;
	static $hNew = 14;
	static $Plus = 15;
	static $Pop = 16;
	static $PopIntoInstanceVar = 17;
	static $PopIntoGlobalVar = 18;
	static $PopIntoProperty = 19;
	static $PushConst = 20;
	static $PushInstanceVar = 21;
	static $PushGlobalVar = 22;
	static $PushModule = 23;
	static $PushProperty = 24;
	static $SubCall = 25;
	static $SubDefine = 26;
	static $SubReturn = 27;
	static $Times = 28;
	function __toString() { return 'constants.Opcode'; }
}
