<?php

// Generated by Haxe 3.4.2
class constants_Opcode {
	public function __construct(){}
	static $CallMemberFn = 1;
	static $Dimension = 2;
	static $Divide = 3;
	static $Eq = 4;
	static $FnCall = 5;
	static $Gt = 6;
	static $Gte = 7;
	static $Jmp = 8;
	static $JmpIfFalse = 9;
	static $Lt = 10;
	static $Lte = 11;
	static $Minus = 12;
	static $Neq = 13;
	static $Plus = 14;
	static $Pop = 15;
	static $PopIntoGlobal = 16;
	static $PopIntoProperty = 17;
	static $PushConst = 18;
	static $PushGlobal = 19;
	static $PushModule = 20;
	static $PushProperty = 21;
	static $SubCall = 22;
	static $SubDefine = 23;
	static $SubReturn = 24;
	static $Times = 25;
	function __toString() { return 'constants.Opcode'; }
}
