<?php

// Generated by Haxe 3.4.2
class constants_Opcode extends Enum {
	public static $FnCall;
	public static $Pop;
	public static $PushConst;
	public static $__constructors = array(0 => 'FnCall', 2 => 'Pop', 1 => 'PushConst');
	}
constants_Opcode::$FnCall = new constants_Opcode("FnCall", 0);
constants_Opcode::$Pop = new constants_Opcode("Pop", 2);
constants_Opcode::$PushConst = new constants_Opcode("PushConst", 1);
