<?php

// Generated by Haxe 3.4.2
class constants_ServiceNames {
	public function __construct(){}
	static $Action = "action";
	static $Handle = "handle";
	function __toString() { return 'constants.ServiceNames'; }
}
