<?php

// Generated by Haxe 3.4.2
class constants_SessionKeys {
	public function __construct(){}
	static $GlobalDictionary = "global_dictionary";
	static $StdModules = "std_modules";
	function __toString() { return 'constants.SessionKeys'; }
}
