<?php

// Generated by Haxe 3.4.2
class runtime_process_MethodContext extends runtime_process_Context {
	public function __construct($compiledMethod) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->compiledMethod = $compiledMethod;
		$this->bytecodes = $compiledMethod->bytecodes;
		$this->literals = $compiledMethod->literals;
	}}
	public $bytecodes;
	public $compiledMethod;
	public $literals;
	public function getProxy($name) {
		if($this->compiledMethod->module === null) {
			return null;
		}
		$module = runtime_globals_GlobalModules::getModule($this->compiledMethod->module);
		return $module->asInstance()->getProxy($name);
	}
	public function setProxy($name, $val) {
		if($this->compiledMethod->module === null) {
			return null;
		}
		$module = runtime_globals_GlobalModules::getModule($this->compiledMethod->module);
		$module->asInstance()->setProxy($name, $val);
		return $name;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'runtime.process.MethodContext'; }
}
