<?php

// Generated by Haxe 3.4.2
class runtime_process_ProcessManager {
	public function __construct() {}
	public function runMethodInline($compiledMethod) {
		$process = runtime_process_Process::fromCompiledMethod($compiledMethod);
		return $process->run();
	}
	static $instance;
	static function runMethod($compiledMethod) {
		return runtime_process_ProcessManager::$instance->runMethodInline($compiledMethod);
	}
	function __toString() { return 'runtime.process.ProcessManager'; }
}
runtime_process_ProcessManager::$instance = new runtime_process_ProcessManager();
