<?php

// Generated by Haxe 3.4.2
class runtime_process_ServiceManager {
	public function __construct(){}
	static function createActionService($object, $action, $args, $afterAppear = null) {
		if($afterAppear === null) {
			$afterAppear = false;
		}
		$value = $object->getId();
		return _hx_anonymous(array("service" => "action", "id" => $value, "action" => $action, "args" => util_NormalizeUtil::normalizeArray($args), "afterAppear" => $afterAppear));
	}
	static function createHandlerService($map) {
		$map->set("service", "handle");
		return util_NormalizeUtil::normalizeMap($map);
	}
	function __toString() { return 'runtime.process.ServiceManager'; }
}
