<?php

// Generated by Haxe 3.4.2
class util_ReadStream {
	public function __construct($src = null) {
		if(!php_Boot::$skip_constructor) {
		if($src === null) {
			$src = "";
		}
		$this->LF = "\x0A";
		$this->CR = "\x0D";
		$this->TAB = "\x09";
		$this->UNDERSCORE = "_";
		$this->SPACE = " ";
		$this->DQUOTE = "\"";
		$this->SQUOTE = "'";
		$this->COLONEQUAL = ":=";
		$this->DOT = ".";
		$this->PLUS = "+";
		$this->FS = "/";
		$this->BS = "\\";
		$this->NE = "<>";
		$this->GTET = ">=";
		$this->LTET = "<=";
		$this->GT = ">";
		$this->LT = "<";
		$this->COLON = ":";
		$this->SEMI = ";";
		$this->EQUAL = "=";
		$this->AST = "*";
		$this->DASH = "-";
		$this->COMMA = ",";
		$this->DOLLAR = "\$";
		$this->AT = "@";
		$this->HASH = "#";
		$this->EXCL = "!";
		$this->CARET = "^";
		$this->AMP = "&";
		$this->PERCENT = "%";
		$this->RP = ")";
		$this->LP = "(";
		$this->RB = "]";
		$this->LB = "[";
		$this->index = -1;
		$this->ch = "";
		$this->src = $src;
	}}
	public $LB;
	public $RB;
	public $LP;
	public $RP;
	public $PERCENT;
	public $AMP;
	public $CARET;
	public $EXCL;
	public $HASH;
	public $AT;
	public $DOLLAR;
	public $COMMA;
	public $DASH;
	public $AST;
	public $EQUAL;
	public $SEMI;
	public $COLON;
	public $LT;
	public $GT;
	public $LTET;
	public $GTET;
	public $NE;
	public $BS;
	public $FS;
	public $PLUS;
	public $DOT;
	public $COLONEQUAL;
	public $SQUOTE;
	public $DQUOTE;
	public $SPACE;
	public $UNDERSCORE;
	public $TAB;
	public $CR;
	public $LF;
	public $index;
	public $ch;
	public $src;
	public function atEof() {
		return $this->index >= strlen($this->src);
	}
	public function isAlphaLower($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		if((strcmp($ch, "a")>= 0)) {
			return (strcmp($ch, "z")<= 0);
		} else {
			return false;
		}
	}
	public function isAlphaUpper($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		if((strcmp($ch, "A")>= 0)) {
			return (strcmp($ch, "Z")<= 0);
		} else {
			return false;
		}
	}
	public function isAmp($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->AMP;
	}
	public function isAssign($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($this->isColon(null)) {
			return $this->isEq($this->peekCh(1));
		} else {
			return false;
		}
	}
	public function isAst($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->AST;
	}
	public function isAt($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->AT;
	}
	public function isBs($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->BS;
	}
	public function isCaret($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->CARET;
	}
	public function isColon($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->COLON;
	}
	public function isComma($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->COMMA;
	}
	public function isCr($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->CR;
	}
	public function isDash($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->DASH;
	}
	public function isDigit($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		if((strcmp($ch, "0")>= 0)) {
			return (strcmp($ch, "9")<= 0);
		} else {
			return false;
		}
	}
	public function isDollar($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->DOLLAR;
	}
	public function isDot($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->DOT;
	}
	public function isDquote($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->DQUOTE;
	}
	public function isEol() {
		if(!$this->atEof()) {
			return $this->isLf(null);
		} else {
			return true;
		}
	}
	public function isEq($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->EQUAL;
	}
	public function isExcl($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->EXCL;
	}
	public function isFs($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->FS;
	}
	public function isGt($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->GT;
	}
	public function isGte($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($this->isGt(null)) {
			return $this->isEq($this->peekCh(1));
		} else {
			return false;
		}
	}
	public function isHash($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->HASH;
	}
	public function isIdCh($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		$tmp = null;
		if(!$this->isLetter($ch)) {
			$tmp = $this->isDigit($ch);
		} else {
			$tmp = true;
		}
		if(!$tmp) {
			return $this->isUnderscore($ch);
		} else {
			return true;
		}
	}
	public function isLb($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->LB;
	}
	public function isLetter($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		if(!$this->isAlphaLower($ch)) {
			return $this->isAlphaUpper($ch);
		} else {
			return true;
		}
	}
	public function isLf($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->LF;
	}
	public function isLp($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->LP;
	}
	public function isLt($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->LT;
	}
	public function isLte($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($this->isLt(null)) {
			return $this->isEq($this->peekCh(1));
		} else {
			return false;
		}
	}
	public function isNeq($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($this->isLt(null)) {
			return $this->isGt($this->peekCh(1));
		} else {
			return false;
		}
	}
	public function isPercent($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->PERCENT;
	}
	public function isPlus($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->PLUS;
	}
	public function isRb($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->RB;
	}
	public function isRp($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->RP;
	}
	public function isSemi($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->SEMI;
	}
	public function isSquote($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->SQUOTE;
	}
	public function isSpace($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->SPACE;
	}
	public function isStringCh($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		if(!$this->atEof()) {
			return $ch !== $this->DQUOTE;
		} else {
			return false;
		}
	}
	public function isTab($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->TAB;
	}
	public function isUnderscore($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		return $ch === $this->UNDERSCORE;
	}
	public function isWhitespace($ch = null) {
		if($ch === null) {
			$ch = "";
		}
		if($ch === "") {
			$ch = $this->ch;
		}
		$tmp = null;
		if(!$this->isSpace($ch)) {
			$tmp = $this->isTab($ch);
		} else {
			$tmp = true;
		}
		if(!$tmp) {
			return $this->isCr($ch);
		} else {
			return true;
		}
	}
	public function nextCh() {
		$this->advance();
		return $this->ch;
	}
	public function peekCh($n = null) {
		if($n === null) {
			$n = 0;
		}
		return _hx_char_at($this->src, $this->index + $n);
	}
	public function advance() {
		if(!$this->atEof()) {
			$this->index++;
		}
		$this->ch = $this->peekCh(null);
	}
	public function setEof() {
		$this->index = strlen($this->src) + 1;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'util.ReadStream'; }
}
