<?php

// Generated by Haxe 3.4.2
class util_StringUtil {
	public function __construct(){}
	static function asNameEventPair($subName) {
		$parts = _hx_explode("_", $subName);
		if($parts->length < 2) {
			return null;
		}
		$eventName = strtolower($parts->pop());
		if(constants_Events::$EventNames->indexOf($eventName, null) < 0) {
			return null;
		}
		$map = new haxe_ds_StringMap();
		$map->set("name", $parts->join("_"));
		$map->set("event", $eventName);
		$map->set("sub", $subName);
		return $map;
	}
	static function isGlobal($s) {
		if(strlen($s) === 0) {
			return false;
		}
		$ch = _hx_char_at($s, 0);
		if((strcmp($ch, "A")>= 0)) {
			return (strcmp($ch, "Z")<= 0);
		} else {
			return false;
		}
	}
	function __toString() { return 'util.StringUtil'; }
}
