<?php

// Generated by Haxe 3.4.2
class util_StringUtil {
	public function __construct(){}
	static function isGlobal($s) {
		if(strlen($s) === 0) {
			return false;
		}
		$ch = _hx_char_at($s, 0);
		if((strcmp($ch, "A")>= 0)) {
			return (strcmp($ch, "Z")<= 0);
		} else {
			return false;
		}
	}
	function __toString() { return 'util.StringUtil'; }
}
