<?php

// Generated by Haxe 3.4.2
class runtime_loader_SessionManager {
	public function __construct(){}
	static function restoreFromSession($sessionStr) {
		runtime_loader_ObjectBuilder::init();
		if($sessionStr !== null) {
			$unserializer = new haxe_Unserializer($sessionStr);
			$storeMap = $unserializer->unserialize();
			runtime_loader_SessionManager::restoreFromMap($storeMap);
		}
	}
	static function storeToSession() {
		$storeMap = new haxe_ds_StringMap();
		runtime_loader_SessionManager::storeToMap($storeMap);
		$serializer = new haxe_Serializer();
		$serializer->serialize($storeMap);
		return $serializer->toString();
	}
	static function restoreFromMap($storeMap) {
		$globalDictionary = $storeMap->get("global_dictionary");
		if($globalDictionary !== null) {
			runtime_globals_GlobalDictionary::setMap($globalDictionary);
		}
		$stdModules = $storeMap->get("std_modules");
		if($stdModules !== null) {
			runtime_globals_GlobalModules::setModules($stdModules);
		}
	}
	static function storeToMap($storeMap) {
		$globalDictionary = runtime_globals_GlobalDictionary::getMap();
		$stdModules = runtime_globals_GlobalModules::getModules();
		$storeMap->set("global_dictionary", $globalDictionary);
		$storeMap->set("std_modules", $stdModules);
	}
	function __toString() { return 'runtime.loader.SessionManager'; }
}
