<?php

// Generated by Haxe 3.4.2
class runtime_functions_Builtins extends runtime_process_ProcessBase {
	public function __construct($methodContext) { if(!php_Boot::$skip_constructor) {
		parent::__construct($methodContext);
	}}
	public function callMemberFn($objectName, $fnName, $args) {
		$map = new haxe_ds_StringMap();
		$object = $this->getObjectName($objectName);
		if($object !== null) {
			$object->callFn($fnName, $args, $map);
			$args1 = $map->get("args");
			$this->actionOutput($object, $map->get("action"), $args1, true);
			return $fnName;
		} else {
			return "object " . _hx_string_or_null($objectName) . " not found";
		}
	}
	public function callSub($name) {
		$subEntry = $this->getGlobalName($name);
		if(!Std::is($subEntry, _hx_qtype("Int"))) {
			return $name;
		}
		$this->pushReturn();
		$this->hgoto($subEntry);
		return $name;
	}
	public function fnCall($lit, $nargs) {
		$nstack = $this->stackSize();
		$name = Std::string($this->literal($lit));
		$val = null;
		if($name === "print") {
			$val = $this->hprint($nargs);
		} else {
			$val = $this->callSub($name);
		}
		$this->popn($nstack - $nargs);
		$this->push($val);
	}
	public function getGlobalName($name) {
		return runtime_globals_GlobalDictionary::$instance->get($name);
	}
	public function getObjectName($name) {
		$val = $this->getGlobalName($name);
		if(Std::is($val, _hx_qtype("runtime.proxies.QkObject"))) {
			return $val;
		} else {
			return null;
		}
	}
	public function getPropertyNames($objectName, $propertyName) {
		$object = $this->getObjectName($objectName);
		if($object !== null) {
			return $object->getProperty($propertyName);
		} else {
			return "object " . _hx_string_or_null($objectName) . " not found";
		}
	}
	public function hprint($nargs) {
		{
			$_g1 = 0;
			$_g = $nargs;
			while($_g1 < $_g) {
				$_g1 = $_g1 + 1;
				$i = $_g1 - 1;
				$this->printOutput(Std::string($this->pop()));
				unset($i);
			}
		}
		return "print " . _hx_string_rec($nargs, "");
	}
	public function setGlobalName($name, $val) {
		runtime_globals_GlobalDictionary::$instance->set($name, $val);
		return $val;
	}
	public function setPropertyNames($objectName, $propertyName, $val) {
		$map = new haxe_ds_StringMap();
		$object = $this->getObjectName($objectName);
		if($object !== null) {
			$object->setProperty($propertyName, $val, $map);
			$args = (new _hx_array(array($map->get("args"))));
			$this->actionOutput($object, $map->get("action"), $args, null);
			return $propertyName;
		} else {
			return "object " . _hx_string_or_null($objectName) . " not found";
		}
	}
	function __toString() { return 'runtime.functions.Builtins'; }
}
