<?php

// Generated by Haxe 3.4.2
class runtime_functions_ModuleFunctions extends runtime_functions_UiFunctions {
	public function __construct($methodContext) { if(!php_Boot::$skip_constructor) {
		parent::__construct($methodContext);
	}}
	public function getModule($name) {
		return runtime_globals_GlobalModules::getModule($name);
	}
	public function pushModule($lit) {
		$name = Std::string($this->literal($lit));
		$module = $this->getModule($name);
		if($module !== null) {
			$this->push($module);
		} else {
			$this->push("module [" . _hx_string_or_null($name) . "] not found");
		}
	}
	function __toString() { return 'runtime.functions.ModuleFunctions'; }
}
